/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PaymentSubmission {
  'id' : bigint,
  'utr' : string,
  'status' : PaymentStatus,
  'userId' : bigint,
  'name' : string,
  'timestamp' : bigint,
  'phone' : string,
  'amount' : string,
}
export interface PaymentSubmissionInput {
  'utr' : string,
  'name' : string,
  'phone' : string,
  'amount' : string,
}
export interface ReferralNode {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'children' : Array<ReferralNode>,
  'phone' : string,
  'referredByName' : string,
}
export interface Transaction {
  'id' : bigint,
  'userId' : bigint,
  'note' : string,
  'timestamp' : bigint,
  'txType' : string,
  'amount' : bigint,
}
export interface User {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'joinedAt' : bigint,
  'role' : string,
  'isPaid' : boolean,
  'isActive' : boolean,
  'email' : string,
  'referredBy' : string,
  'phone' : string,
  'walletBalance' : bigint,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'duration' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'channelUrl' : string,
  'thumbnailUrl' : string,
}
export interface WatchRecord {
  'userId' : bigint,
  'completed' : boolean,
  'watchedSeconds' : bigint,
  'subscribed' : boolean,
  'videoId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideo' : ActorMethod<[string, string, string, string, bigint], undefined>,
  'addVideoWithPassword' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'deletePaymentSubmissionWithPassword' : ActorMethod<
    [string, bigint],
    undefined
  >,
  'deleteUser' : ActorMethod<[bigint], undefined>,
  'deleteUserWithPassword' : ActorMethod<[string, bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'deleteVideoWithPassword' : ActorMethod<[string, bigint], undefined>,
  'updateVideoChannelInfoWithPassword' : ActorMethod<[string, bigint, string, string], undefined>,
  'forceSetAdmin' : ActorMethod<[string], string>,
  'getAllPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getAllPaymentSubmissionsWithPassword' : ActorMethod<
    [string],
    Array<PaymentSubmission>
  >,
  'getAllReferralTreesWithPassword' : ActorMethod<
    [string],
    Array<
      {
        'totalNetwork' : bigint,
        'directReferrals' : bigint,
        'referralCode' : string,
        'userId' : bigint,
        'name' : string,
        'isPaid' : boolean,
        'phone' : string,
      }
    >
  >,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllUsersWithPassword' : ActorMethod<[string], Array<User>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getAllVideosPublic' : ActorMethod<[], Array<Video>>,
  'getVideosByCategoryPublic' : ActorMethod<[string], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getMyProfile' : ActorMethod<[bigint], User>,
  'getMyWatchHistory' : ActorMethod<[], Array<WatchRecord>>,
  'getReferralTree' : ActorMethod<[bigint], ReferralNode>,
  'getReferralTreeByCode' : ActorMethod<
    [string],
    {
      'id' : bigint,
      'referralCode' : string,
      'name' : string,
      'children' : Array<ReferralNode>,
      'phone' : string,
      'referredByName' : string,
    }
  >,
  'getReferralTreeByPhoneWithPassword' : ActorMethod<
    [string, string],
    [] | [
      {
        'id' : bigint,
        'referralCode' : string,
        'name' : string,
        'children' : Array<ReferralNode>,
        'phone' : string,
        'referredByName' : string,
      }
    ]
  >,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserByPhone' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordWatchProgress' : ActorMethod<[bigint, bigint, boolean], undefined>,
  'register' : ActorMethod<[string, string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentProof' : ActorMethod<[PaymentSubmissionInput], bigint>,
  'updateUser' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateUserStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateUserStatusWithPassword' : ActorMethod<
    [string, bigint, boolean],
    undefined
  >,
  'updateUserWithPassword' : ActorMethod<
    [string, bigint, string, string, string, boolean],
    undefined
  >,
  'verifyPaymentSubmission' : ActorMethod<[bigint, string], undefined>,
  'verifyPaymentSubmissionWithPassword' : ActorMethod<
    [string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];