/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReferralNode = IDL.Rec();
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserChannel = IDL.Record({
  'id' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'ownerPhone' : IDL.Text,
  'description' : IDL.Text,
  'bannerUrl' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentSubmission = IDL.Record({
  'id' : IDL.Nat,
  'utr' : IDL.Text,
  'status' : PaymentStatus,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'amount' : IDL.Text,
});
export const UserVideo = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'channelId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'ownerPhone' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : IDL.Text,
  'isPaid' : IDL.Bool,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'referredBy' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'channelUrl' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
ReferralNode.fill(
  IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'children' : IDL.Vec(ReferralNode),
    'phone' : IDL.Text,
    'referredByCode' : IDL.Text,
    'referredByName' : IDL.Text,
  })
);
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'documentUrl' : IDL.Text,
  'userId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
});
export const PaymentSubmissionInput = IDL.Record({
  'utr' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChannelWithPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addVideoWithPassword' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannelWithPhone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteChannelVideoWithPhone' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteChannelWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteChannelWithPasswordById' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePaymentSubmissionWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteUserVideoWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteUserWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteVideoWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'editUserWithPassword' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllChannelsListWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChannelLink)],
      ['query'],
    ),
  'getAllChannelsPublic' : IDL.Func([], [IDL.Vec(UserChannel)], ['query']),
  'getAllChannelsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserChannel)],
      ['query'],
    ),
  'getAllPaymentSubmissionsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentSubmission)],
      ['query'],
    ),
  'getAllUserVideosWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserVideo)],
      ['query'],
    ),
  'getAllUsersWatchTimeWithPassword' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'totalSeconds' : IDL.Nat,
            'userId' : IDL.Nat,
            'name' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllUsersWithPassword' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelVideos' : IDL.Func([IDL.Nat], [IDL.Vec(UserVideo)], ['query']),
  'getJoiningBonus' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyChannelByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserChannel)],
      ['query'],
    ),
  'getReferralTreeByUserId' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ReferralNode)],
      ['query'],
    ),
  'getReferralTreeWithPassword' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [ReferralNode],
      ['query'],
    ),
  'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWatchTime' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserWatchTimeByPhone' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'getWithdrawalRequestsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'initializeAdmin' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordWatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool], [], []),
  'recordWatchByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'rejectPaymentSubmissionWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setJoiningBonusWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitPaymentProof' : IDL.Func([PaymentSubmissionInput], [IDL.Nat], []),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateChannelWithPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateWithdrawalStatusWithPassword' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'uploadVideoToChannelWithPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'verifyPaymentSubmissionWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReferralNode = IDL.Rec();
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserChannel = IDL.Record({
    'id' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'ownerPhone' : IDL.Text,
    'description' : IDL.Text,
    'bannerUrl' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentSubmission = IDL.Record({
    'id' : IDL.Nat,
    'utr' : IDL.Text,
    'status' : PaymentStatus,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'amount' : IDL.Text,
  });
  const UserVideo = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'channelId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'ownerPhone' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : IDL.Text,
    'isPaid' : IDL.Bool,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'referredBy' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'channelUrl' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  ReferralNode.fill(
    IDL.Record({
      'id' : IDL.Nat,
      'referralCode' : IDL.Text,
      'name' : IDL.Text,
      'children' : IDL.Vec(ReferralNode),
      'phone' : IDL.Text,
      'referredByCode' : IDL.Text,
      'referredByName' : IDL.Text,
    })
  );
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'documentUrl' : IDL.Text,
    'userId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentSubmissionInput = IDL.Record({
    'utr' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChannelWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addVideoWithPassword' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannelWithPhone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteChannelVideoWithPhone' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteChannelWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteChannelWithPasswordById' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePaymentSubmissionWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteUserVideoWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteUserWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteVideoWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'editUserWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllChannelsListWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChannelLink)],
        ['query'],
      ),
    'getAllChannelsPublic' : IDL.Func([], [IDL.Vec(UserChannel)], ['query']),
    'getAllChannelsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserChannel)],
        ['query'],
      ),
    'getAllPaymentSubmissionsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'getAllUserVideosWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserVideo)],
        ['query'],
      ),
    'getAllUsersWatchTimeWithPassword' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'totalSeconds' : IDL.Nat,
              'userId' : IDL.Nat,
              'name' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllUsersWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(User)],
        ['query'],
      ),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelVideos' : IDL.Func([IDL.Nat], [IDL.Vec(UserVideo)], ['query']),
    'getJoiningBonus' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyChannelByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserChannel)],
        ['query'],
      ),
    'getReferralTreeByUserId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReferralNode)],
        ['query'],
      ),
    'getReferralTreeWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [ReferralNode],
        ['query'],
      ),
    'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWatchTime' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserWatchTimeByPhone' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'getWithdrawalRequestsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'initializeAdmin' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordWatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool], [], []),
    'recordWatchByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'rejectPaymentSubmissionWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setJoiningBonusWithPassword' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitPaymentProof' : IDL.Func([PaymentSubmissionInput], [IDL.Nat], []),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateChannelWithPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateWithdrawalStatusWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'uploadVideoToChannelWithPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'verifyPaymentSubmissionWithPassword' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };