/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PaymentSubmission {
  'id' : bigint,
  'utr' : string,
  'status' : PaymentStatus,
  'userId' : bigint,
  'name' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PaymentSubmissionInput {
  'utr' : string,
  'name' : string,
  'phone' : string,
}
export interface ReferralNode {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'children' : Array<ReferralNode>,
}
export interface Transaction {
  'id' : bigint,
  'userId' : bigint,
  'note' : string,
  'timestamp' : bigint,
  'txType' : string,
  'amount' : bigint,
}
export interface User {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'joinedAt' : bigint,
  'role' : string,
  'isPaid' : boolean,
  'isActive' : boolean,
  'email' : string,
  'referredBy' : string,
  'phone' : string,
  'walletBalance' : bigint,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'duration' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
}
export interface WatchRecord {
  'userId' : bigint,
  'completed' : boolean,
  'watchedSeconds' : bigint,
  'subscribed' : boolean,
  'videoId' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideo' : ActorMethod<[string, string, string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getAllPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getMyProfile' : ActorMethod<[bigint], User>,
  'getMyWatchHistory' : ActorMethod<[bigint], Array<WatchRecord>>,
  'getReferralTree' : ActorMethod<[bigint], ReferralNode>,
  'getTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordWatchProgress' : ActorMethod<
    [bigint, bigint, bigint, boolean],
    undefined
  >,
  'register' : ActorMethod<[string, string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentProof' : ActorMethod<[PaymentSubmissionInput], bigint>,
  'updateUserStatus' : ActorMethod<[bigint, boolean], undefined>,
  'verifyPaymentSubmission' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];