/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReferralNode = IDL.Rec();
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : IDL.Text,
  'isPaid' : IDL.Bool,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'referredBy' : IDL.Text,
  'phone' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const WatchRecord = IDL.Record({
  'userId' : IDL.Nat,
  'completed' : IDL.Bool,
  'watchedSeconds' : IDL.Nat,
  'subscribed' : IDL.Bool,
  'videoId' : IDL.Nat,
});
ReferralNode.fill(
  IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'children' : IDL.Vec(ReferralNode),
  })
);
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Nat,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([IDL.Nat], [User], ['query']),
  'getMyWatchHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WatchRecord)], ['query']),
  'getReferralTree' : IDL.Func([IDL.Nat], [ReferralNode], ['query']),
  'getTransactions' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordWatchProgress' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReferralNode = IDL.Rec();
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : IDL.Text,
    'isPaid' : IDL.Bool,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'referredBy' : IDL.Text,
    'phone' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const WatchRecord = IDL.Record({
    'userId' : IDL.Nat,
    'completed' : IDL.Bool,
    'watchedSeconds' : IDL.Nat,
    'subscribed' : IDL.Bool,
    'videoId' : IDL.Nat,
  });
  ReferralNode.fill(
    IDL.Record({
      'id' : IDL.Nat,
      'referralCode' : IDL.Text,
      'name' : IDL.Text,
      'children' : IDL.Vec(ReferralNode),
    })
  );
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Nat,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([IDL.Nat], [User], ['query']),
    'getMyWatchHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WatchRecord)],
        ['query'],
      ),
    'getReferralTree' : IDL.Func([IDL.Nat], [ReferralNode], ['query']),
    'getTransactions' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordWatchProgress' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };