/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: bigint;
    url: string;
    channelUrl: string;
    title: string;
    duration: bigint;
    thumbnailUrl: string;
    createdAt: bigint;
    description: string;
    category: string;
}
export interface PaymentSubmissionInput {
    utr: string;
    name: string;
    phone: string;
    amount: string;
}
export interface PaymentSubmission {
    id: bigint;
    utr: string;
    status: PaymentStatus;
    userId: bigint;
    name: string;
    timestamp: bigint;
    phone: string;
    amount: string;
}
export interface User {
    id: bigint;
    referralCode: string;
    name: string;
    joinedAt: bigint;
    role: string;
    isPaid: boolean;
    isActive: boolean;
    email: string;
    referredBy: string;
    phone: string;
    walletBalance: bigint;
}
export interface UserChannel {
    id: bigint;
    thumbnailUrl: string;
    name: string;
    createdAt: bigint;
    ownerPhone: string;
    description: string;
    bannerUrl: string;
}
export interface UserVideo {
    id: bigint;
    url: string;
    status: string;
    title: string;
    thumbnailUrl: string;
    channelId: bigint;
    createdAt: bigint;
    ownerPhone: string;
    description: string;
    category: string;
}
export interface ChannelLink {
    id: bigint;
    url: string;
    name: string;
    createdAt: bigint;
}
export interface UserProfile {
    userId: bigint;
    name: string;
    email: string;
    phone: string;
}
export interface ReferralNode {
    id: bigint;
    referralCode: string;
    name: string;
    children: Array<ReferralNode>;
    phone: string;
    referredByName: string;
}
export enum PaymentStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChannelWithPassword(password: string, name: string, url: string): Promise<bigint>;
    addVideoWithPassword(password: string, title: string, category: string, url: string, description: string, duration: bigint, channelUrl: string, thumbnailUrl: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChannelWithPhone(phone: string, name: string, description: string, thumbnailUrl: string, bannerUrl: string): Promise<bigint>;
    deleteChannelVideoWithPhone(phone: string, videoId: bigint): Promise<void>;
    deleteChannelWithPassword(password: string, channelId: bigint): Promise<void>;
    deleteChannelWithPasswordById(password: string, channelId: bigint): Promise<void>;
    deletePaymentSubmissionWithPassword(password: string, submissionId: bigint): Promise<void>;
    deleteUserVideoWithPassword(password: string, videoId: bigint): Promise<void>;
    deleteUserWithPassword(password: string, userId: bigint): Promise<void>;
    deleteVideoWithPassword(password: string, videoId: bigint): Promise<void>;
    editUserWithPassword(password: string, userId: bigint, name: string, email: string, phone: string): Promise<void>;
    getAllChannelsListWithPassword(password: string): Promise<Array<ChannelLink>>;
    getAllChannelsPublic(): Promise<Array<UserChannel>>;
    getAllChannelsWithPassword(password: string): Promise<Array<UserChannel>>;
    getAllPaymentSubmissionsWithPassword(password: string): Promise<Array<PaymentSubmission>>;
    getAllUserVideosWithPassword(password: string): Promise<Array<UserVideo>>;
    getAllUsersWatchTimeWithPassword(password: string): Promise<Array<{
        totalSeconds: bigint;
        userId: bigint;
        name: string;
        phone: string;
    }>>;
    getAllUsersWithPassword(password: string): Promise<Array<User>>;
    getAllVideos(): Promise<Array<Video>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannelVideos(channelId: bigint): Promise<Array<UserVideo>>;
    getMyChannelByPhone(phone: string): Promise<UserChannel | null>;
    getReferralTreeWithPassword(password: string, userId: bigint): Promise<ReferralNode>;
    getUserByPhone(phone: string): Promise<User | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWatchTime(phone: string): Promise<bigint>;
    getUserWatchTimeByPhone(phone: string): Promise<bigint>;
    getVideosByCategory(category: string): Promise<Array<Video>>;
    initializeAdmin(userProvidedToken: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordWatch(videoId: bigint, watchedSeconds: bigint, completed: boolean, subscribed: boolean): Promise<void>;
    recordWatchByPhone(phone: string, videoId: bigint, watchedSeconds: bigint, completed: boolean, subscribed: boolean): Promise<void>;
    registerUser(name: string, email: string, phone: string, referralCode: string): Promise<bigint>;
    rejectPaymentSubmissionWithPassword(password: string, submissionId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPaymentProof(input: PaymentSubmissionInput): Promise<bigint>;
    updateChannelWithPhone(phone: string, channelId: bigint, name: string, description: string, thumbnailUrl: string, bannerUrl: string): Promise<void>;
    uploadVideoToChannelWithPhone(phone: string, channelId: bigint, title: string, url: string, description: string, thumbnailUrl: string, category: string): Promise<bigint>;
    verifyPaymentSubmissionWithPassword(password: string, submissionId: bigint): Promise<void>;
}
import type { PaymentStatus as _PaymentStatus, PaymentSubmission as _PaymentSubmission, ReferralNode as _ReferralNode, User as _User, UserChannel as _UserChannel, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChannelWithPassword(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChannelWithPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChannelWithPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async addVideoWithPassword(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoWithPassword(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoWithPassword(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChannelWithPhone(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannelWithPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannelWithPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteChannelVideoWithPhone(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannelVideoWithPhone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannelVideoWithPhone(arg0, arg1);
            return result;
        }
    }
    async deleteChannelWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannelWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannelWithPassword(arg0, arg1);
            return result;
        }
    }
    async deleteChannelWithPasswordById(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannelWithPasswordById(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannelWithPasswordById(arg0, arg1);
            return result;
        }
    }
    async deletePaymentSubmissionWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePaymentSubmissionWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePaymentSubmissionWithPassword(arg0, arg1);
            return result;
        }
    }
    async deleteUserVideoWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserVideoWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserVideoWithPassword(arg0, arg1);
            return result;
        }
    }
    async deleteUserWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserWithPassword(arg0, arg1);
            return result;
        }
    }
    async deleteVideoWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoWithPassword(arg0, arg1);
            return result;
        }
    }
    async editUserWithPassword(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editUserWithPassword(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editUserWithPassword(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllChannelsListWithPassword(arg0: string): Promise<Array<ChannelLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannelsListWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannelsListWithPassword(arg0);
            return result;
        }
    }
    async getAllChannelsPublic(): Promise<Array<UserChannel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannelsPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannelsPublic();
            return result;
        }
    }
    async getAllChannelsWithPassword(arg0: string): Promise<Array<UserChannel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannelsWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannelsWithPassword(arg0);
            return result;
        }
    }
    async getAllPaymentSubmissionsWithPassword(arg0: string): Promise<Array<PaymentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPaymentSubmissionsWithPassword(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPaymentSubmissionsWithPassword(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserVideosWithPassword(arg0: string): Promise<Array<UserVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserVideosWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserVideosWithPassword(arg0);
            return result;
        }
    }
    async getAllUsersWatchTimeWithPassword(arg0: string): Promise<Array<{
        totalSeconds: bigint;
        userId: bigint;
        name: string;
        phone: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWatchTimeWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWatchTimeWithPassword(arg0);
            return result;
        }
    }
    async getAllUsersWithPassword(arg0: string): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithPassword(arg0);
            return result;
        }
    }
    async getAllVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelVideos(arg0: bigint): Promise<Array<UserVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelVideos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelVideos(arg0);
            return result;
        }
    }
    async getMyChannelByPhone(arg0: string): Promise<UserChannel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChannelByPhone(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChannelByPhone(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralTreeWithPassword(arg0: string, arg1: bigint): Promise<ReferralNode> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralTreeWithPassword(arg0, arg1);
                return from_candid_ReferralNode_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralTreeWithPassword(arg0, arg1);
            return from_candid_ReferralNode_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPhone(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPhone(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPhone(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWatchTime(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWatchTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWatchTime(arg0);
            return result;
        }
    }
    async getUserWatchTimeByPhone(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWatchTimeByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWatchTimeByPhone(arg0);
            return result;
        }
    }
    async getVideosByCategory(arg0: string): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(arg0);
            return result;
        }
    }
    async initializeAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordWatch(arg0: bigint, arg1: bigint, arg2: boolean, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordWatchByPhone(arg0: string, arg1: bigint, arg2: bigint, arg3: boolean, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWatchByPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWatchByPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectPaymentSubmissionWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPaymentSubmissionWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPaymentSubmissionWithPassword(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPaymentProof(arg0: PaymentSubmissionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentProof(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentProof(arg0);
            return result;
        }
    }
    async updateChannelWithPhone(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannelWithPhone(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannelWithPhone(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async uploadVideoToChannelWithPhone(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideoToChannelWithPhone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideoToChannelWithPhone(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async verifyPaymentSubmissionWithPassword(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPaymentSubmissionWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPaymentSubmissionWithPassword(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PaymentStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentSubmission_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentSubmission): PaymentSubmission {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReferralNode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralNode): ReferralNode {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserChannel]): UserChannel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    referralCode: string;
    name: string;
    children: Array<_ReferralNode>;
    phone: string;
    referredByName: string;
}): {
    id: bigint;
    referralCode: string;
    name: string;
    children: Array<ReferralNode>;
    phone: string;
    referredByName: string;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        name: value.name,
        children: from_candid_vec_n14(_uploadFile, _downloadFile, value.children),
        phone: value.phone,
        referredByName: value.referredByName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    utr: string;
    status: _PaymentStatus;
    userId: bigint;
    name: string;
    timestamp: bigint;
    phone: string;
    amount: string;
}): {
    id: bigint;
    utr: string;
    status: PaymentStatus;
    userId: bigint;
    name: string;
    timestamp: bigint;
    phone: string;
    amount: string;
} {
    return {
        id: value.id,
        utr: value.utr,
        status: from_candid_PaymentStatus_n6(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        name: value.name,
        timestamp: value.timestamp,
        phone: value.phone,
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "approved" in value ? PaymentStatus.approved : "rejected" in value ? PaymentStatus.rejected : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReferralNode>): Array<ReferralNode> {
    return value.map((x)=>from_candid_ReferralNode_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentSubmission>): Array<PaymentSubmission> {
    return value.map((x)=>from_candid_PaymentSubmission_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
